"""
Curated activity metadata for the Destiny 2 Boss Drops app.

- The FULL, accurate loot pool for each activity is auto-derived from the Bungie
  manifest's DestinyCollectibleDefinition `sourceString` (see ingest.py).
- Here we curate the human-facing structure: activity metadata, ordered
  encounters/bosses, and (where confidently known) which WEAPONS drop from which
  encounter. Any pool weapon not explicitly assigned falls into "shared" drops;
  all armor is grouped into the activity's armor set automatically.

`source_match` is a lowercase substring matched against the collectible source
string to collect that activity's items.
"""

ACTIVITIES = [
    # ============================ RAIDS ============================
    {
        "id": "vault_of_glass",
        "name": "Vault of Glass",
        "type": "raid",
        "location": "Venus",
        "release": "2021",
        "activity_match": "vault of glass",
        "source_match": ["vault of glass"],
        "description": "Venture deep into the Vault of Glass and stop the Vex from mastering the fabric of time itself, ending with the time-bending mind Atheon.",
        "encounters": [
            {"name": "The Confluxes", "boss": "Praetorian Confluxes", "weapons": ["Vision of Confluence", "Corrective Measure"]},
            {"name": "The Templar", "boss": "Templar", "weapons": ["Fatebringer", "Hezen Vengeance"]},
            {"name": "The Gatekeepers", "boss": "Gatekeeper Wyverns", "weapons": ["Found Verdict", "Praedyth's Revenge"]},
            {"name": "Atheon, Time's Conflux", "boss": "Atheon, Time's Conflux", "weapons": ["Vex Mythoclast"]},
        ],
    },
    {
        "id": "deep_stone_crypt",
        "name": "Deep Stone Crypt",
        "type": "raid",
        "location": "Europa",
        "release": "2020",
        "activity_match": "deep stone crypt",
        "source_match": ["deep stone crypt"],
        "description": "Descend into the Deep Stone Crypt beneath Europa's ice to stop the House of Salvation and the Fallen mercenary Taniks.",
        "encounters": [
            {"name": "Crypt Security", "boss": "Security Systems", "weapons": ["Trustee", "Heritage"]},
            {"name": "Atraks-1, Fallen Exo", "boss": "Atraks-1, Fallen Exo", "weapons": ["Succession"]},
            {"name": "Descent", "boss": "Nuclear Descent", "weapons": ["Posterity"]},
            {"name": "Taniks, the Abomination", "boss": "Taniks, the Abomination", "weapons": ["Commemoration", "Bequest", "Eyes of Tomorrow"]},
        ],
    },
    {
        "id": "garden_of_salvation",
        "name": "Garden of Salvation",
        "type": "raid",
        "location": "Black Garden",
        "release": "2019",
        "activity_match": "garden of salvation",
        "source_match": ["garden of salvation"],
        "description": "Follow the Unraveler's trail into the Black Garden and sever the Vex's connection to the Darkness within the Consecrated Mind.",
        "encounters": [
            {"name": "Embrace / Evasion", "boss": "The Embrace", "weapons": ["Zealot's Reward"]},
            {"name": "Summoning Ritual", "boss": "Consecrated Mind (Undying)", "weapons": ["Reckless Oracle", "Ancient Gospel"]},
            {"name": "Consecrated Mind", "boss": "Consecrated Mind, Sol Inheritor", "weapons": ["Prophet of Doom", "Divinity"]},
            {"name": "Sanctified Mind", "boss": "Sanctified Mind, Sol Inheritor", "weapons": ["Sacred Provenance", "Omniscient Eye"]},
        ],
    },
    {
        "id": "last_wish",
        "name": "Last Wish",
        "type": "raid",
        "location": "Dreaming City",
        "release": "2018",
        "activity_match": "last wish",
        "source_match": ["last wish"],
        "description": "Confront Riven of a Thousand Voices, the last known Ahamkara, deep within the Dreaming City to break Queen Mara Sov's curse.",
        "encounters": [
            {"name": "Kalli, the Corrupted", "boss": "Kalli, the Corrupted", "weapons": ["Nation of Beasts", "Techeun Force"]},
            {"name": "Shuro Chi, the Corrupted", "boss": "Shuro Chi, the Corrupted", "weapons": ["Chattering Bone", "Age-Old Bond"]},
            {"name": "Morgeth, the Spirekeeper", "boss": "Morgeth, the Spirekeeper", "weapons": ["Transfiguration"]},
            {"name": "The Vault (Shuro's Riddle)", "boss": "The Vault", "weapons": ["Tyranny of Heaven"]},
            {"name": "Riven of a Thousand Voices", "boss": "Riven of a Thousand Voices", "weapons": ["Apex Predator", "One Thousand Voices"]},
        ],
    },
    {
        "id": "vow_of_the_disciple",
        "name": "Vow of the Disciple",
        "type": "raid",
        "location": "Savathûn's Throne World",
        "release": "2022",
        "activity_match": "vow of the disciple",
        "source_match": ["vow of the disciple"],
        "description": "Breach the sunken pyramid in Savathûn's Throne World and end the Disciple of the Witness, Rhulk.",
        "encounters": [
            {"name": "Acquisition", "boss": "The Disciple's Bog", "weapons": ["Submission"]},
            {"name": "The Caretaker", "boss": "The Caretaker", "weapons": ["Deliverance", "Cataclysmic"]},
            {"name": "Exhibition", "boss": "The Exhibition", "weapons": ["Insidious"]},
            {"name": "Rhulk, Disciple of the Witness", "boss": "Rhulk, Disciple of the Witness", "weapons": ["Forbearance", "Lubrae's Ruin", "Collective Obligation"]},
        ],
    },
    {
        "id": "kings_fall",
        "name": "King's Fall",
        "type": "raid",
        "location": "Dreadnaught",
        "release": "2022",
        "activity_match": "king's fall",
        "source_match": ["king's fall", "kings fall"],
        "description": "Board the Dreadnaught and slay Oryx, the Taken King, in this returning classic raid.",
        "encounters": [
            {"name": "The Basilica", "boss": "Tomb Ships & Totems", "weapons": ["Doom of Chelchis"]},
            {"name": "Warpriest", "boss": "The Warpriest", "weapons": ["Zaouli's Bane"]},
            {"name": "Golgoroth", "boss": "Golgoroth", "weapons": ["Smite of Merain"]},
            {"name": "Daughters of Oryx", "boss": "The Daughters of Oryx", "weapons": ["Qullim's Terminus", "Defiance of Yasmin"]},
            {"name": "Oryx, the Taken King", "boss": "Oryx, the Taken King", "weapons": ["Midha's Reckoning", "Touch of Malice"]},
        ],
    },
    {
        "id": "root_of_nightmares",
        "name": "Root of Nightmares",
        "type": "raid",
        "location": "Essence (Neomuna)",
        "release": "2023",
        "activity_match": "root of nightmares",
        "source_match": ["root of nightmares"],
        "description": "Board the Essence and stop Nezarec, the Final God of Pain, from awakening aboard the derelict Pyramid ship.",
        "encounters": [
            {"name": "Cataclysm", "boss": "The Cataclysm", "weapons": ["Rufus's Fury"]},
            {"name": "Scission", "boss": "Scission", "weapons": ["Koraxis's Distress"]},
            {"name": "Macrocosm", "boss": "Macrocosm", "weapons": ["Nessa's Oblation", "Mykel's Reverence"]},
            {"name": "Nezarec, Final God of Pain", "boss": "Nezarec, Final God of Pain", "weapons": ["Briar's Contempt", "Conditional Finality"]},
        ],
    },
    {
        "id": "crotas_end",
        "name": "Crota's End",
        "type": "raid",
        "location": "The Moon",
        "release": "2023",
        "activity_match": "crota's end",
        "source_match": ["crota's end", "crotas end"],
        "description": "Descend into the Hellmouth and end Crota, Son of Oryx, in this returning Destiny classic raid.",
        "encounters": [
            {"name": "The Abyss", "boss": "The Abyss", "weapons": ["Abyss Defiant"]},
            {"name": "The Bridge", "boss": "Ir Yût's Bridge", "weapons": ["Fang of Ir Yût", "Swordbreaker"]},
            {"name": "Ir Yût, the Deathsinger", "boss": "Ir Yût, the Deathsinger", "weapons": ["Song of Ir Yût"]},
            {"name": "Crota, Son of Oryx", "boss": "Crota, Son of Oryx", "weapons": ["Word of Crota", "Oversoul Edict", "Necrochasm"]},
        ],
    },
    {
        "id": "salvations_edge",
        "name": "Salvation's Edge",
        "type": "raid",
        "location": "The Pale Heart",
        "release": "2024",
        "activity_match": "salvation's edge",
        "source_match": ["salvation's edge", "salvations edge"],
        "description": "Enter the Witness's monolith within the Pale Heart of the Traveler and stop the Final Shape.",
        "encounters": [
            {"name": "Substratum", "boss": "Substratum", "weapons": []},
            {"name": "Dissection", "boss": "Dissection", "weapons": []},
            {"name": "Repository", "boss": "Repository", "weapons": []},
            {"name": "Verity", "boss": "Verity", "weapons": []},
            {"name": "The Witness", "boss": "The Witness", "weapons": []},
        ],
    },
    # ============================ DUNGEONS ============================
    {
        "id": "shattered_throne",
        "name": "The Shattered Throne",
        "type": "dungeon",
        "location": "The Dreaming City",
        "release": "2018",
        "activity_match": "shattered throne",
        "source_match": ["shattered throne"],
        "description": "Delve into the Ascendant Plane to defeat Dûl Incaru and weaken the curse of the Dreaming City.",
        "encounters": [
            {"name": "Vorgeth, the Boundless Hunger", "boss": "Vorgeth, the Boundless Hunger", "weapons": []},
            {"name": "Dûl Incaru, the Eternal Return", "boss": "Dûl Incaru, the Eternal Return", "weapons": ["Wish-Ender"]},
        ],
    },
    {
        "id": "pit_of_heresy",
        "name": "Pit of Heresy",
        "type": "dungeon",
        "location": "The Moon",
        "release": "2019",
        "activity_match": "pit of heresy",
        "source_match": ["pit of heresy"],
        "description": "Descend into the Scarlet Keep's depths and destroy the Hive god of death's chosen, Zulmak.",
        "encounters": [
            {"name": "The Necropolis", "boss": "The Necropolis", "weapons": []},
            {"name": "Tunnels of Despair", "boss": "Chamber Ogres", "weapons": []},
            {"name": "The Harrowing", "boss": "Knight Trials", "weapons": ["Premonition"]},
            {"name": "Zulmak, Instrument of Torment", "boss": "Zulmak, Instrument of Torment", "weapons": []},
        ],
    },
    {
        "id": "prophecy",
        "name": "Prophecy",
        "type": "dungeon",
        "location": "The Nine's Realm",
        "release": "2020",
        "activity_match": "prophecy",
        "source_match": ["prophecy"],
        "description": "Journey into the realm of the Nine to restore balance between Light and Darkness.",
        "encounters": [
            {"name": "Phalanx Echo", "boss": "Phalanx Echo", "weapons": ["Prosecutor", "Adjudicator"]},
            {"name": "The Hexahedron", "boss": "Cube Guardians", "weapons": ["Judgment"]},
            {"name": "Kell Echo", "boss": "Kell Echo", "weapons": ["Death Adder"]},
        ],
    },
    {
        "id": "grasp_of_avarice",
        "name": "Grasp of Avarice",
        "type": "dungeon",
        "location": "The Cosmodrome",
        "release": "2021",
        "activity_match": "grasp of avarice",
        "source_match": ["grasp of avarice"],
        "description": "Follow the trail of Fallen greed into the Loot Cave and claim the wealth of Wilhelm-7 — and Gjallarhorn.",
        "encounters": [
            {"name": "Phry'zhia, the Insatiable", "boss": "Phry'zhia, the Insatiable", "weapons": ["Eyasluna"]},
            {"name": "Captain Avarokk, the Covetous", "boss": "Captain Avarokk, the Covetous", "weapons": ["Matador 64", "1000-Yard Stare", "Gjallarhorn"]},
        ],
    },
    {
        "id": "duality",
        "name": "Duality",
        "type": "dungeon",
        "location": "The Leviathan (Bound Presence)",
        "release": "2022",
        "activity_match": "duality",
        "source_match": ["duality"],
        "description": "Enter Emperor Calus's mind aboard the Leviathan and confront the Nightmares that haunt him.",
        "encounters": [
            {"name": "Nightmare of Gahlran", "boss": "Nightmare of Gahlran", "weapons": ["Unforgiven", "The Epicurean"]},
            {"name": "Nightmare of Caiatl", "boss": "Nightmare of Caiatl", "weapons": ["Fixed Odds", "Lingering Dread", "Heartshadow"]},
        ],
    },
    {
        "id": "spire_of_the_watcher",
        "name": "Spire of the Watcher",
        "type": "dungeon",
        "location": "Mars (Seraph Station)",
        "release": "2022",
        "activity_match": "spire of the watcher",
        "source_match": ["spire of the watcher"],
        "description": "Climb the Seraph spire on Mars and stop the rogue Warmind subroutine Persys.",
        "encounters": [
            {"name": "The Ascent", "boss": "The Ascent", "weapons": ["Liminal Vigil"]},
            {"name": "Akelous, the Siren's Current", "boss": "Akelous, the Siren's Current", "weapons": ["Long Arm", "Wilderflight"]},
            {"name": "Persys, Primordial Ruin", "boss": "Persys, Primordial Ruin", "weapons": ["Terminus Horizon", "Hierarchy of Needs"]},
        ],
    },
    {
        "id": "ghosts_of_the_deep",
        "name": "Ghosts of the Deep",
        "type": "dungeon",
        "location": "Titan (Methane Sea)",
        "release": "2023",
        "activity_match": "ghosts of the deep",
        "source_match": ["ghosts of the deep"],
        "description": "Dive beneath Titan's methane sea to end Savathûn's lingering Hive and the worm god's chosen.",
        "encounters": [
            {"name": "Ecthar, the Shield of Savathûn", "boss": "Ecthar, the Shield of Savathûn", "weapons": ["New Pacific Epitaph", "Greasy Luck"]},
            {"name": "Simmumah ur-Nokru", "boss": "Simmumah ur-Nokru", "weapons": ["Cold Comfort", "Tinasha's Mastery", "The Navigator"]},
        ],
    },
    {
        "id": "warlords_ruin",
        "name": "Warlord's Ruin",
        "type": "dungeon",
        "location": "The Shattered Throne (Ruined Keep)",
        "release": "2023",
        "activity_match": "warlord's ruin",
        "source_match": ["warlord's ruin", "warlords ruin"],
        "description": "Break the curse of the warlord Fikrul and end Rathil's dark ritual in this frozen keep.",
        "encounters": [
            {"name": "Rathil, First Disciple of Fikrul", "boss": "Rathil, First Disciple of Fikrul", "weapons": []},
            {"name": "Hefnd's Vengeance", "boss": "Hefnd's Vengeance, Locus of Wailing Grief", "weapons": ["Buried Bloodline"]},
        ],
    },
    {
        "id": "vespers_host",
        "name": "Vesper's Host",
        "type": "dungeon",
        "location": "The Derelict Seraph Station",
        "release": "2024",
        "activity_match": "vesper's host",
        "source_match": ["vesper's host", "vespers host"],
        "description": "Board the derelict Seraph station overrun by the Scorn and recover the reforged Ice Breaker.",
        "encounters": [
            {"name": "Raneiks Unified", "boss": "Raneiks Unified", "weapons": []},
            {"name": "The Corrupted Puppeteer", "boss": "The Corrupted Puppeteer", "weapons": ["Ice Breaker"]},
        ],
    },
    {
        "id": "sundered_doctrine",
        "name": "Sundered Doctrine",
        "type": "dungeon",
        "location": "The Pale Heart (Rectifier)",
        "release": "2025",
        "activity_match": "sundered doctrine",
        "source_match": ["sundered doctrine"],
        "description": "Decode the Witness's final secrets within the Rectifier and confront what remains of its doctrine.",
        "encounters": [
            {"name": "Zoetic Lockset", "boss": "Zoetic Lockset", "weapons": []},
            {"name": "Kerapis, Sundered by Doctrine", "boss": "Kerapis, Sundered by Doctrine", "weapons": []},
        ],
    },
    # ============================ NIGHTFALL ============================
    {
        "id": "nightfall_ordeal",
        "name": "Nightfall: The Ordeal",
        "type": "nightfall",
        "location": "Vanguard Ops",
        "release": "Weekly Rotator",
        "activity_match": "nightfall",
        "source_match": ["source: nightfall", "grandmaster nightfall"],
        "description": "The pinnacle of Vanguard Strikes. Each week a different Strike enters the Ordeal rotation with a featured weapon reward pool \u2014 clear Grandmaster for Adept variants.",
        "encounters": [],
    },
    # ============================ WORLD ============================
    {
        "id": "the_wellspring",
        "name": "The Wellspring",
        "type": "world",
        "location": "Savath\u00fbn's Throne World",
        "release": "2022",
        "activity_match": "wellspring",
        "source_match": ["wellspring boss"],
        "description": "A rotating public activity in Savath\u00fbn's Throne World. Each of the four rotating bosses guards a specific craftable weapon \u2014 attack or defend the Wellspring to earn it.",
        "encounters": [
            {"name": "Attack \u00b7 Zeerik", "boss": "Zeerik, Lightflayer", "weapons": ["Father's Sins"]},
            {"name": "Defend \u00b7 Golmag", "boss": "Golmag, Warden of the Spring", "weapons": ["Come to Pass"]},
            {"name": "Attack \u00b7 Bor'gong", "boss": "Bor'gong, Warden of the Spring", "weapons": ["Fel Taradiddle"]},
            {"name": "Defend \u00b7 Vezuul", "boss": "Vezuul, Lightflayer", "weapons": ["Tarnation"]},
        ],
    },
    {
        "id": "exotic_missions",
        "name": "Exotic Missions",
        "type": "world",
        "location": "Various Destinations",
        "release": "Rotator",
        "activity_match": "presage",
        "source_match": [
            "vox obscura", "presage", "seraph's shield", "avalon",
            "the whisper", "zero hour", "starcrossed", "encore",
        ],
        "description": "Bespoke story missions that each culminate in a unique Exotic reward. Complete them (some on a weekly rotation) to earn their signature weapons.",
        "encounters": [
            {"name": "Presage", "boss": "Nightmare Aboard the Glykon", "weapons": ["Dead Man's Tale"]},
            {"name": "Vox Obscura", "boss": "Ravener, Hand of Xivu Arath", "weapons": ["Dead Messenger"]},
            {"name": "Operation: Seraph's Shield", "boss": "Warmind Vault Core", "weapons": ["Revision Zero"]},
            {"name": "//node.ovrd.AVALON//", "boss": "The Vault Subroutine", "weapons": ["Vexcalibur"]},
            {"name": "The Whisper", "boss": "Taken Blights of the Whisper", "weapons": ["Whisper of the Worm", "Karve of the Worm"]},
            {"name": "Zero Hour", "boss": "The Insurrection Prime", "weapons": ["Outbreak Perfected", "Vimana Junker"]},
            {"name": "Starcrossed", "boss": "Herald of Finality", "weapons": ["Wish-Keeper"]},
            {"name": "Exotic Mission: Encore", "boss": "The Witness's Echo", "weapons": ["Choir of One"]},
        ],
    },
    # ============================ CRUCIBLE (PvP RITUALS) ============================
    {
        "id": "trials_of_osiris",
        "name": "Trials of Osiris",
        "type": "crucible",
        "location": "The Crucible \u00b7 Weekend",
        "release": "Weekly Rotator",
        "activity_match": "trials of osiris",
        "source_match": ["trials of osiris", "emissary of the nine", "flawless trials"],
        "description": "The pinnacle of competitive PvP. Win matches on a Trials ticket \u2014 and go Flawless \u2014 to earn the featured weekly weapon and Adept rewards from the Lighthouse.",
        "encounters": [],
    },
    {
        "id": "iron_banner",
        "name": "Iron Banner",
        "type": "crucible",
        "location": "The Crucible \u00b7 Lord Saladin",
        "release": "Seasonal Rotator",
        "activity_match": "iron banner",
        "source_match": ["iron banner", "lord saladin"],
        "description": "Lord Saladin's periodic 6v6 power-enabled Crucible event. Play matches and rank up reputation to earn the Iron Banner weapon and armor set.",
        "encounters": [],
    },
]
